### ISSUE TITLE
wave writer output continue to write endlessy

### ISSUE THREAD

**Issue by ciros88** [aargirakis/BZRPlayer#557] opened 2024-10-22 10:20 UTC
set wave writer, add a track, play it without any loop set:
*.wav writing will continue after the track playback is finished or manually stopped

**Comment by aargirakis** [comment] 2024-10-22 18:15
Duplicate of #441

**Comment by aargirakis** [comment] 2024-10-23 06:31
Will still write endlessly when starting the program or when setting output to wav writer.

**Closed** 2024-10-25 18:32 UTC
Labels: bug
