### ISSUE TITLE
[psflib][psf2lib] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#236] opened 2022-11-05 12:07 UTC
Found 2 audio formats that can't be played in BZR2.

BZR's Version: 2.0.25 Alpha

Note: Probably they r music files, bcuz some of them named as BGM.

Some samples:

[psflib.zip](https://github.com/aargirakis/BZRPlayer/files/9943737/psflib.zip)

[psf2lib.zip](https://github.com/aargirakis/BZRPlayer/files/9943738/psf2lib.zip)

**Comment by ciros88** [comment] 2022-11-05 18:16
close as duplicate of #235

**Closed by ciros88** 2022-11-05 18:16 UTC
