### ISSUE TITLE
[minipsf][minipsf2] Not playable

### ISSUE THREAD

**Issue by rayman3003** [aargirakis/BZRPlayer#221] opened 2022-11-05 10:46 UTC
Found audio formats that can't be played in BZR2.

BZR's Version: 2.0.25 Alpha

Note: I'm almost sure that they r music files, bcuz a lot of them named as BGM.

Some samples:

[minipsf.zip](https://github.com/aargirakis/BZRPlayer/files/9943578/minipsf.zip)

[minipsf2.zip](https://github.com/aargirakis/BZRPlayer/files/9943581/minipsf2.zip)

**Comment by ciros88** [comment] 2022-11-05 18:06
close as duplicate of #235

**Closed by ciros88** 2022-11-05 18:06 UTC
